export const BATTLE_TIME_LIMIT_MS = 1000000;
export const FURY_BURST_THRESHOLD = 300;
export const PARRY_PERCENT_PER_RES = 0.02;
export const CRIT_PERCENT_PER_CRT = 0.04;
export const DODGE_PERCENT_PER_EVA = 0.06;
export const SKILL_TRIGGER_PERCENT_PER_HIT = 0.01;
